"""Build data/lookup/areas.json (+ SOURCE.md) — DOPA admin codes + MOPH health-region table.

Sources (recorded verbatim in data/lookup/SOURCE.md):
  * kongvut/thai-province-data (GitHub, DOPA-derived): province / district / sub_district JSON.
    NOTE: its `province_id` is an internal sequence, NOT the DOPA code; the DOPA province code is
    district_id // 100 (e.g. 1501 -> 15 = อ่างทอง), the district code is `district.id` (4 digits) and
    the subdistrict code is `sub_district.id` (6 digits).
  * MOPH province -> health region (เขตสุขภาพ) table, MOPH 13 regions (healthserv.net/1330).
"""
from __future__ import annotations

import json
from datetime import date
from pathlib import Path

import certifi
import requests

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "lookup" / "areas.json"
SRC_MD = ROOT / "data" / "lookup" / "SOURCE.md"
CACHE = ROOT / "data" / "raw_api" / "_lookup"

BASE = "https://raw.githubusercontent.com/kongvut/thai-province-data/master/api/latest/"
FILES = ["province.json", "district.json", "sub_district.json"]
REGION_URL = "https://healthserv.net/1330"

# MOPH health regions (เขตสุขภาพ) — province names as written by MOPH
REGIONS = {
    1: "เชียงใหม่ เชียงราย แพร่ น่าน พะเยา ลำปาง ลำพูน แม่ฮ่องสอน",
    2: "ตาก เพชรบูรณ์ พิษณุโลก อุตรดิตถ์ สุโขทัย",
    3: "กำแพงเพชร พิจิตร นครสวรรค์ ชัยนาท อุทัยธานี",
    4: "สระบุรี นนทบุรี ลพบุรี อ่างทอง นครนายก สิงห์บุรี พระนครศรีอยุธยา ปทุมธานี",
    5: "เพชรบุรี สมุทรสาคร สมุทรสงคราม ประจวบคีรีขันธ์ สุพรรณบุรี นครปฐม ราชบุรี กาญจนบุรี",
    6: "สระแก้ว ปราจีนบุรี ฉะเชิงเทรา สมุทรปราการ ชลบุรี จันทบุรี ระยอง ตราด",
    7: "กาฬสินธุ์ ขอนแก่น มหาสารคาม ร้อยเอ็ด",
    8: "อุดรธานี สกลนคร นครพนม เลย หนองคาย หนองบัวลำภู บึงกาฬ",
    9: "ชัยภูมิ นครราชสีมา บุรีรัมย์ สุรินทร์",
    10: "อุบลราชธานี ศรีสะเกษ ยโสธร มุกดาหาร อำนาจเจริญ",  # ยโสธร is missing from the healthserv page; added (verified vs Excel region-10 totals)
    11: "นครศรีธรรมราช สุราษฎร์ธานี ภูเก็ต กระบี่ พังงา ระนอง ชุมพร",
    12: "สงขลา สตูล ตรัง พัทลุง ปัตตานี ยะลา นราธิวาส",
    13: "กรุงเทพมหานคร",
}


def _get(name: str, refresh: bool):
    p = CACHE / name
    if p.exists() and not refresh:
        return json.loads(p.read_text(encoding="utf-8"))
    r = requests.get(BASE + name, timeout=120, verify=certifi.where())
    r.raise_for_status()
    CACHE.mkdir(parents=True, exist_ok=True)
    p.write_bytes(r.content)
    return r.json()


def build(refresh: bool = False) -> dict:
    prov_raw, dist_raw, sub_raw = (_get(f, refresh) for f in FILES)
    prov_name_by_internal = {p["id"]: p["name_th"] for p in prov_raw}
    region_of_name = {}
    for reg, names in REGIONS.items():
        for n in names.split():
            if n in region_of_name:
                raise SystemExit(f"province listed twice in region table: {n}")
            region_of_name[n] = reg

    districts, provinces = {}, {}
    for d in dist_raw:
        code = str(d["id"])
        districts[code] = d["name_th"]
        pc = code[:-2]
        provinces[pc] = prov_name_by_internal[d["province_id"]]
    subdistricts = {str(s["id"]): s["name_th"] for s in sub_raw}

    if len(provinces) != 77:
        raise SystemExit(f"expected 77 provinces, got {len(provinces)}")
    missing = [n for n in provinces.values() if n not in region_of_name]
    extra = [n for n in region_of_name if n not in set(provinces.values())]
    if missing or extra:
        raise SystemExit(f"region table mismatch: missing={missing} extra={extra}")

    out = {
        "provinces": {pc: {"name": provinces[pc], "region": region_of_name[provinces[pc]]}
                      for pc in sorted(provinces, key=int)},
        "districts": dict(sorted(districts.items())),
        "subdistricts": dict(sorted(subdistricts.items())),
        "regions": {str(i): f"เขตสุขภาพที่ {i}" for i in range(1, 14)},
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=1), encoding="utf-8")
    SRC_MD.write_text(f"""# Source of data/lookup/areas.json

Generated by `python3 scripts/kpi.py lookup` (scripts/build_lookup.py) on {date.today().isoformat()}.

## Administrative codes (DOPA-derived, open data)
- {BASE}province.json
- {BASE}district.json
- {BASE}sub_district.json

Repository: https://github.com/kongvut/thai-province-data (province/district/sub-district names and codes
of Thailand). Its `province_id` is an internal sequence, not the DOPA code, so the DOPA province code is
taken as `district.id // 100`; district code = `district.id` (4 digits); subdistrict code = `sub_district.id`
(6 digits). Result: 77 provinces, {len(districts)} districts, {len(subdistricts)} subdistricts.

## Province -> health region (เขตสุขภาพ) table
- {REGION_URL}  (MOPH 13 health regions, province lists; page also mentions NHSO regions, which are ignored)
- The healthserv page lists only 4 provinces for region 10 (ยโสธร is omitted, 76 of 77 provinces); ยโสธร was
  added to region 10 manually (MOPH region 10 = 5 provinces) and is verified by the Excel region-10 totals.
- Cross-check: a web-search summary of MOPH / regional-office pages agreed for regions 1-3 and 8-13 (not fetched in
  full); the whole table is validated by
  `kpi.py verify` (Coverage API grouped by this table must equal the HDC Excel `เขตสุขภาพ` country files 100%).

## Mandatory checks (performed in `kpi.py verify`, hard errors)
- the 7 district names and 14 subdistrict names of Angthong equal the names in the HDC Excel files;
- region 4 = นครนายก นนทบุรี ปทุมธานี พระนครศรีอยุธยา ลพบุรี สระบุรี สิงห์บุรี อ่างทอง.
""", encoding="utf-8")
    return out


if __name__ == "__main__":
    a = build()
    print(len(a["provinces"]), len(a["districts"]), len(a["subdistricts"]))
