"""Build data/lookup/areas.json — DOPA admin codes + MOPH health-region table — and the unit registry units.json.

data/lookup/SOURCE.md is hand-kept; build() only rewrites the block between its `areas:begin` / `areas:end` markers.
Sources:
  * kongvut/thai-province-data (GitHub, DOPA-derived): province / district / sub_district JSON.
    NOTE: its `province_id` is an internal sequence, NOT the DOPA code; the DOPA province code is
    district_id // 100 (e.g. 1501 -> 15 = อ่างทอง), the district code is `district.id` (4 digits) and
    the subdistrict code is `sub_district.id` (6 digits).
  * MOPH province -> health region (เขตสุขภาพ) table, MOPH 13 regions (healthserv.net/1330).
"""
from __future__ import annotations

import json
from datetime import date
from pathlib import Path

import certifi
import requests

from .indicators.common import fallback_tambon
from .loaders import moph_api

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "lookup" / "areas.json"
UNITS = ROOT / "data" / "lookup" / "units.json"
GIS_URL = "https://opendata-service.moph.go.th/gis/v1/getgis/hoscode/{hoscode}"
SRC_MD = ROOT / "data" / "lookup" / "SOURCE.md"
CACHE = ROOT / "data" / "raw_api" / "_lookup"

BASE = "https://raw.githubusercontent.com/kongvut/thai-province-data/master/api/latest/"
FILES = ["province.json", "district.json", "sub_district.json"]
REGION_URL = "https://healthserv.net/1330"

# MOPH health regions (เขตสุขภาพ) — province names as written by MOPH
REGIONS = {
    1: "เชียงใหม่ เชียงราย แพร่ น่าน พะเยา ลำปาง ลำพูน แม่ฮ่องสอน",
    2: "ตาก เพชรบูรณ์ พิษณุโลก อุตรดิตถ์ สุโขทัย",
    3: "กำแพงเพชร พิจิตร นครสวรรค์ ชัยนาท อุทัยธานี",
    4: "สระบุรี นนทบุรี ลพบุรี อ่างทอง นครนายก สิงห์บุรี พระนครศรีอยุธยา ปทุมธานี",
    5: "เพชรบุรี สมุทรสาคร สมุทรสงคราม ประจวบคีรีขันธ์ สุพรรณบุรี นครปฐม ราชบุรี กาญจนบุรี",
    6: "สระแก้ว ปราจีนบุรี ฉะเชิงเทรา สมุทรปราการ ชลบุรี จันทบุรี ระยอง ตราด",
    7: "กาฬสินธุ์ ขอนแก่น มหาสารคาม ร้อยเอ็ด",
    8: "อุดรธานี สกลนคร นครพนม เลย หนองคาย หนองบัวลำภู บึงกาฬ",
    9: "ชัยภูมิ นครราชสีมา บุรีรัมย์ สุรินทร์",
    10: "อุบลราชธานี ศรีสะเกษ ยโสธร มุกดาหาร อำนาจเจริญ",  # ยโสธร is missing from the healthserv page; added (verified vs Excel region-10 totals)
    11: "นครศรีธรรมราช สุราษฎร์ธานี ภูเก็ต กระบี่ พังงา ระนอง ชุมพร",
    12: "สงขลา สตูล ตรัง พัทลุง ปัตตานี ยะลา นราธิวาส",
    13: "กรุงเทพมหานคร",
}


def _get(name: str, refresh: bool):
    p = CACHE / name
    if p.exists() and not refresh:
        return json.loads(p.read_text(encoding="utf-8"))
    r = requests.get(BASE + name, timeout=120, verify=certifi.where())
    r.raise_for_status()
    CACHE.mkdir(parents=True, exist_ok=True)
    p.write_bytes(r.content)
    return r.json()


SRC_BEGIN = "<!-- areas:begin (generated by scripts/build_lookup.py - edit the template there) -->"
SRC_END = "<!-- areas:end -->"


def _areas_source_block(n_districts: int, n_subdistricts: int) -> str:
    return f"""{SRC_BEGIN}
Generated by `python3 scripts/kpi.py lookup` (scripts/build_lookup.py) on {date.today().isoformat()}.

## Administrative codes (DOPA-derived, open data)
- {BASE}province.json
- {BASE}district.json
- {BASE}sub_district.json

Repository: https://github.com/kongvut/thai-province-data (province/district/sub-district names and codes
of Thailand). Its `province_id` is an internal sequence, not the DOPA code, so the DOPA province code is
taken as `district.id // 100`; district code = `district.id` (4 digits); subdistrict code = `sub_district.id`
(6 digits). Result: 77 provinces, {n_districts} districts, {n_subdistricts} subdistricts.
{SRC_END}"""


def _write_source_md(n_districts: int, n_subdistricts: int) -> None:
    """Replace only the generated areas block of SOURCE.md; the rest of the file (health-region table, unit
    registry, mandatory checks) is hand-kept and left untouched."""
    block = _areas_source_block(n_districts, n_subdistricts)
    if not SRC_MD.exists():
        SRC_MD.write_text(f"# Source of data/lookup/areas.json\n\n{block}\n", encoding="utf-8")
        return
    text = SRC_MD.read_text(encoding="utf-8")
    if SRC_BEGIN not in text or SRC_END not in text:
        print(f"WARN {SRC_MD.relative_to(ROOT)}: areas markers missing -> not updated")
        return
    head, rest = text.split(SRC_BEGIN, 1)
    SRC_MD.write_text(head + block + rest.split(SRC_END, 1)[1], encoding="utf-8")


def build(refresh: bool = False) -> dict:
    prov_raw, dist_raw, sub_raw = (_get(f, refresh) for f in FILES)
    prov_name_by_internal = {p["id"]: p["name_th"] for p in prov_raw}
    region_of_name = {}
    for reg, names in REGIONS.items():
        for n in names.split():
            if n in region_of_name:
                raise SystemExit(f"province listed twice in region table: {n}")
            region_of_name[n] = reg

    districts, provinces = {}, {}
    for d in dist_raw:
        code = str(d["id"])
        districts[code] = d["name_th"]
        pc = code[:-2]
        provinces[pc] = prov_name_by_internal[d["province_id"]]
    subdistricts = {str(s["id"]): s["name_th"] for s in sub_raw}

    if len(provinces) != 77:
        raise SystemExit(f"expected 77 provinces, got {len(provinces)}")
    missing = [n for n in provinces.values() if n not in region_of_name]
    extra = [n for n in region_of_name if n not in set(provinces.values())]
    if missing or extra:
        raise SystemExit(f"region table mismatch: missing={missing} extra={extra}")

    out = {
        "provinces": {pc: {"name": provinces[pc], "region": region_of_name[provinces[pc]]}
                      for pc in sorted(provinces, key=int)},
        "districts": dict(sorted(districts.items())),
        "subdistricts": dict(sorted(subdistricts.items())),
        "regions": {str(i): f"เขตสุขภาพที่ {i}" for i in range(1, 14)},
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=1), encoding="utf-8")
    _write_source_md(len(districts), len(subdistricts))
    return out


# ------------------------------------------------------------------ unit registry (spec Phase 2 §4.3)
def load_units() -> dict:
    """Whole units.json (units, missing and the optional hand-kept `overrides` — every key is returned)."""
    if UNITS.exists():
        return json.loads(UNITS.read_text(encoding="utf-8"))
    return {"schema": 1, "source": GIS_URL, "fetchedAt": None, "units": {}, "missing": {}}


class GisUnavailable(RuntimeError):
    """The MOPH GIS registry could not be reached / answered for a unit (after all retries)."""


def _gis(hoscode: str):
    """GeoJSON of one unit from the MOPH GIS registry -> dict | None (None = confirmed not in the registry).
    moph_api.retry: 3 retries (5/15/45 s) on network errors / non-200 (timeout = 15 s connect, 60 s read); a 404 or
    an empty feature list means 'not found'. Raises GisUnavailable when every retry failed (registry down != unit
    not found)."""
    def once():
        r = requests.get(GIS_URL.format(hoscode=hoscode), timeout=(15, 60), verify=certifi.where())
        if r.status_code == 404:
            return None
        if r.status_code != 200:
            raise moph_api.Retry(f"HTTP {r.status_code}")
        j = r.json()
        feats = j.get("features") if isinstance(j, dict) else None
        if not feats:
            return None
        pr = feats[0].get("properties") or {}
        if not (pr.get("provcode") and pr.get("distcode") and pr.get("subdistcode")):
            return None
        prov, dist, sub = (str(pr.get(k)).zfill(2) for k in ("provcode", "distcode", "subdistcode"))
        return {"name": (pr.get("hosname") or "").strip(), "tambon": prov + dist + sub,
                "hostype": str(pr.get("hostype") or ""), "dep": str(pr.get("dep") or "")}
    try:
        return moph_api.retry(once, what=f"GIS lookup {hoscode}")
    except moph_api.RetryExhausted as e:
        raise GisUnavailable(f"GIS registry failed for {hoscode}: {e}") from None


def _write_units(reg: dict, path: Path | None = None) -> None:
    """Write the registry. `overrides` (hand-kept per-unit locations, dspm.resolve_tambons) is never produced by the
    fetcher, so the value currently ON DISK is kept as it is (also if reg was loaded before it was edited)."""
    path = path or UNITS
    if path.exists():
        keep = json.loads(path.read_text(encoding="utf-8")).get("overrides")
        if keep is not None:
            reg["overrides"] = keep
    path.write_text(json.dumps(reg, ensure_ascii=False, indent=1), encoding="utf-8")


def units(hospcodes: dict, refresh: bool = False, log=print) -> dict:
    """Incrementally update data/lookup/units.json.
    hospcodes: {hospcode: {"target": int, "areas": {areacode6: target}}} — every unit seen in the raw data (used to
    record the fallback info of units the registry does not know). Codes already present are not fetched again
    unless refresh=True; codes whose last lookup failed (`missing[h]["gisError"]`) are retried every run.
    A registry outage never aborts the run: the failed code gets the fallback this run (marked with `gisError` +
    `gisFailedAt` in `missing`, cleared automatically once a later lookup succeeds or confirms 'not found'); a unit
    already in `units` keeps its entry. After 3 consecutive failures the remaining codes are skipped for this run
    (circuit breaker). Returns the registry dict."""
    from datetime import datetime, timezone
    reg = load_units()
    known = set(reg["units"]) | set(reg["missing"])
    retry = {h for h, m in reg["missing"].items() if isinstance(m, dict) and "gisError" in m}
    todo = sorted(h for h in hospcodes if refresh or h not in known or h in retry)
    failed: dict[str, str] = {}
    consecutive, max_consecutive = 0, 3
    if todo:
        log(f"units: fetching {len(todo)} hospcode(s) from the MOPH GIS registry ...")
    for i, h in enumerate(todo, 1):
        if consecutive >= max_consecutive:
            failed[h] = f"skipped after {max_consecutive} consecutive registry failures"
            continue
        try:
            info = _gis(h)
        except GisUnavailable as e:
            consecutive += 1
            failed[h] = str(e)
            log(f"  WARN GIS registry unavailable for {h}: {e} -> fallback this run, retried next run")
            if consecutive >= max_consecutive:
                skipped = len(todo) - i
                log(f"  WARN {max_consecutive} consecutive registry failures -> skipping the remaining {skipped} "
                    f"hospcode(s) this run (fallback, retried next run)")
        else:
            consecutive = 0
            if info:
                reg["units"][h] = info
                reg["missing"].pop(h, None)
            else:
                reg["units"].pop(h, None)
        if i % 50 == 0 or i == len(todo):
            log(f"  [{i}/{len(todo)}]")
    # fallback record for every unit not in the registry (refreshed from the current data every run).
    # maxTargetArea uses the targets summed over all years: informational only - the web locates each unit per
    # year (dspm.resolve_tambons -> common.fallback_tambon on that year's areas).
    failed_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
    for h, info in hospcodes.items():
        if h in reg["units"]:
            continue
        areas = dict(sorted(info["areas"].items()))
        reg["missing"][h] = {"maxTargetArea": fallback_tambon(areas), "target": info["target"], "areas": areas}
        if h in failed:
            reg["missing"][h]["gisError"] = failed[h]
            reg["missing"][h]["gisFailedAt"] = failed_at
    reg["units"] = dict(sorted(reg["units"].items()))
    reg["missing"] = dict(sorted(reg["missing"].items()))
    if todo or not UNITS.exists():
        reg["fetchedAt"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
    reg["source"] = GIS_URL
    _write_units(reg)
    tail = f" · {len(failed)} registry lookup(s) failed (fallback, retry next run)" if failed else ""
    log(f"units: {len(reg['units'])} in registry, {len(reg['missing'])} not found (fallback) -> {UNITS.relative_to(ROOT)}{tail}")
    return reg
